baseurl = "https://robmeyer.net"
title = "Rob Meyer"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
RelativeURLs = true
CanonifyURLs = true

#disqusShortname = "yourdiscussshortname"

[Permalinks] # https://gohugo.io/content-management/urls/#permalinks
    posts = ":year/:month/:filename"

[params]
    author = "Rob Meyer"
    info = "dev, cyclist, father, maker, photographer..."
    description = "Rob Meyer's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"
    favicon = "/images/favicon.ico"

 #   footercontent = "Enter a text here."

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true

    colorscheme = "auto"
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    icon = "ğŸ‘¨ğŸ»â€ğŸ’» Github"
    weight = 1
    url = "https://github.com/robmeyer/"
[[params.social]]
    name = "LinkedIn"
    icon = "ğŸ“„ LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/rob-meyer/"
[[params.social]]
    name = "Instagram"
    icon = "ğŸ“¸ Instagram"
    weight = 2
    url = "https://www.instagram.com/robmeyer/"
[[params.social]]
    name = "Strava"
    icon = "ğŸš² Strava"
    weight = 2
    url = "https://www.strava.com/athletes/6106508"
[[params.social]]
    name = "Thingiverse"
    icon = "ğŸ› ï¸ Thingiverse"
    weight = 2
    url = "https://www.thingiverse.com/RobMeyer/about"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
